spring:
    application:
        name: bootcamp.project

    datasource:
        url: ${DATABASE_URL:jdbc:postgresql://localhost:25432/npl_project}
        username: ${POSTGRES_USER}
        password: ${POSTGRES_PASSWORD}
        driver-class-name: org.postgresql.Driver

    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        show-sql: true

    flyway:
        enabled: true

    main:
        allow-bean-definition-overriding: true
    springdoc:
        swagger-ui:
            path: /swagger-ui.html